"""Put text at the cursor of the frontmost app.

Default: write the text to the clipboard, press Cmd+V, then restore the
previous clipboard (all types) unless something else changed it meanwhile.
Alternative: synthesize typing (no clipboard, slower, newlines become spaces).
"""

from __future__ import annotations

import logging
import time

import objc
import Quartz
from AppKit import (
    NSPasteboard,
    NSPasteboardContentsCurrentHostOnly,
    NSPasteboardItem,
    NSPasteboardTypeString,
    NSWorkspace,
)
from Foundation import NSData

from .config import Settings
from .hotkey import SYNTHETIC_MARKER
from .paths import BUNDLE_ID

log = logging.getLogger(__name__)

V_KEYCODE = 9  # ANSI "V"; the same key on U.S. and Turkish-Q layouts
COMMAND_KEYCODE = 55
RETURN_KEYCODE = 36
_CMD = Quartz.kCGEventFlagMaskCommand
# Tell clipboard managers (and macOS clipboard history) not to keep our text.
_MARKER_TYPES = (
    "org.nspasteboard.TransientType",
    "org.nspasteboard.AutoGeneratedType",
    "org.nspasteboard.ConcealedType",
)
_MAX_SNAPSHOT_BYTES = 50 * 1024 * 1024
_TYPE_CHUNK_UNITS = 20  # CGEventKeyboardSetUnicodeString limit (UTF-16 units)

Snapshot = list[list[tuple[str, NSData]]]


class TextInserter:
    def can_insert(self) -> bool:
        """Without Accessibility permission macOS silently drops synthetic keys."""
        return bool(Quartz.CGPreflightPostEventAccess())

    def frontmost_pid(self) -> int | None:
        with objc.autorelease_pool():
            app = NSWorkspace.sharedWorkspace().frontmostApplication()
            return int(app.processIdentifier()) if app is not None else None

    def copy(self, text: str) -> None:
        with objc.autorelease_pool():
            _write_private(NSPasteboard.generalPasteboard(), text)

    def insert(self, text: str, settings: Settings, submit: bool) -> None:
        with objc.autorelease_pool():
            snapshot, change_count = None, None
            if text:
                if settings.trailing_space and not submit and not text.endswith((" ", "\n")):
                    text += " "
                if settings.insert_method == "type":
                    self._type(text)
                else:
                    snapshot, change_count = self._paste(text, settings.restore_clipboard)
            if submit:
                time.sleep(0.15 if text else 0.0)
                self._post_key(RETURN_KEYCODE, 0)
            if snapshot is not None:
                time.sleep(settings.restore_delay_ms / 1000)
                pasteboard = NSPasteboard.generalPasteboard()
                if pasteboard.changeCount() == change_count:
                    _restore(pasteboard, snapshot)
                else:
                    log.info("Clipboard changed meanwhile; not restoring it")

    def _paste(self, text: str, restore: bool) -> tuple[Snapshot | None, int]:
        pasteboard = NSPasteboard.generalPasteboard()
        snapshot = _snapshot(pasteboard) if restore else None
        change_count = _write_private(pasteboard, text)
        time.sleep(0.05)  # let the pasteboard settle before the app reads it
        source = Quartz.CGEventSourceCreate(Quartz.kCGEventSourceStatePrivate)
        # Flags are set explicitly so a still-held hotkey cannot turn Cmd+V into Cmd+Opt+V.
        for keycode, down, flags, pause in (
            (COMMAND_KEYCODE, True, _CMD, 0.015),
            (V_KEYCODE, True, _CMD, 0.015),
            (V_KEYCODE, False, _CMD, 0.03),
            (COMMAND_KEYCODE, False, 0, 0.0),
        ):
            _post(source, keycode, down, flags)
            time.sleep(pause)
        return snapshot, change_count

    def _type(self, text: str) -> None:
        text = text.replace("\r\n", "\n").replace("\r", "\n").replace("\n", " ")  # "\n" would submit in terminals
        source = Quartz.CGEventSourceCreate(Quartz.kCGEventSourceStatePrivate)
        for chunk in _utf16_chunks(text, _TYPE_CHUNK_UNITS):
            units = len(chunk.encode("utf-16-le")) // 2
            for down in (True, False):
                event = Quartz.CGEventCreateKeyboardEvent(source, 0, down)
                Quartz.CGEventSetFlags(event, 0)
                Quartz.CGEventKeyboardSetUnicodeString(event, units, chunk)
                Quartz.CGEventSetIntegerValueField(event, Quartz.kCGEventSourceUserData, SYNTHETIC_MARKER)
                Quartz.CGEventPost(Quartz.kCGHIDEventTap, event)
            time.sleep(0.004)

    def _post_key(self, keycode: int, flags: int) -> None:
        source = Quartz.CGEventSourceCreate(Quartz.kCGEventSourceStatePrivate)
        _post(source, keycode, True, flags)
        time.sleep(0.015)
        _post(source, keycode, False, flags)


def _post(source, keycode: int, down: bool, flags: int) -> None:  # noqa: ANN001 - CGEventSource
    event = Quartz.CGEventCreateKeyboardEvent(source, keycode, down)
    Quartz.CGEventSetFlags(event, flags)
    Quartz.CGEventSetIntegerValueField(event, Quartz.kCGEventSourceUserData, SYNTHETIC_MARKER)
    Quartz.CGEventPost(Quartz.kCGHIDEventTap, event)


def _write_private(pasteboard: NSPasteboard, text: str) -> int:
    """Put text on the clipboard for this Mac only (no Universal Clipboard),
    marked so clipboard managers do not keep it. Returns the change count."""
    pasteboard.prepareForNewContentsWithOptions_(NSPasteboardContentsCurrentHostOnly)
    item = NSPasteboardItem.alloc().init()
    item.setString_forType_(text, NSPasteboardTypeString)
    for marker in _MARKER_TYPES:
        item.setData_forType_(NSData.data(), marker)
    item.setString_forType_(BUNDLE_ID, "org.nspasteboard.source")
    pasteboard.writeObjects_([item])
    return pasteboard.changeCount()


def _utf16_chunks(text: str, max_units: int) -> list[str]:
    chunks, current, units = [], [], 0
    for char in text:
        size = 2 if ord(char) > 0xFFFF else 1
        if units + size > max_units:
            chunks.append("".join(current))
            current, units = [], 0
        current.append(char)
        units += size
    if current:
        chunks.append("".join(current))
    return chunks


def _snapshot(pasteboard: NSPasteboard) -> Snapshot | None:
    items: Snapshot = []
    total = 0
    for item in pasteboard.pasteboardItems() or []:
        entries = []
        for kind in item.types() or []:
            data = item.dataForType_(kind)
            if data is None:
                continue
            total += data.length()
            if total > _MAX_SNAPSHOT_BYTES:
                log.info("Clipboard is too large to restore; leaving the dictated text on it")
                return None
            entries.append((kind, data))
        items.append(entries)
    return items


def _restore(pasteboard: NSPasteboard, snapshot: Snapshot) -> None:
    # Host-only: the snapshot can't tell whether the original was, so never widen its reach.
    pasteboard.prepareForNewContentsWithOptions_(NSPasteboardContentsCurrentHostOnly)
    objects = []
    for entries in snapshot:
        item = NSPasteboardItem.alloc().init()
        for kind, data in entries:
            item.setData_forType_(data, kind)
        objects.append(item)
    if objects:
        pasteboard.writeObjects_(objects)
