"""What each platform must provide. The rest of Dikte is platform-neutral."""

from __future__ import annotations

from pathlib import Path
from typing import Callable, Protocol

from ..controller import Status

Action = Callable[[], None]
Warning = tuple[str, Action | None]  # text shown in the menu, optional fix action


class Runtime(Protocol):
    """Main loop and desktop integration."""

    def call_on_main(self, fn: Callable, *args: object) -> None:
        """Run fn on the UI thread (called from worker threads)."""

    def add_timer(self, seconds: float, fn: Action) -> None: ...

    def run(self) -> int:
        """Enter the main loop; returns the exit code."""

    def quit(self) -> None: ...

    def restart(self) -> None: ...

    def open_path(self, path: Path) -> None:
        """Open a file with the user's default application."""


class Tray(Protocol):
    def set_status(self, status: Status) -> None: ...
    def set_history(self, items: tuple[str, ...]) -> None: ...
    def refresh(self) -> None: ...
    def remove(self) -> None: ...


class Hud(Protocol):
    def show(self, text: str, kind: str, level: float | None) -> None:
        """kind: "recording" or "transcribing"."""

    def hide(self) -> None: ...


class NullHud:
    """For desktops that cannot place an always-on-top overlay (Wayland)."""

    def show(self, text: str, kind: str, level: float | None) -> None:
        pass

    def hide(self) -> None:
        pass


class HotkeyBackend(Protocol):
    @property
    def running(self) -> bool: ...
    def start(self) -> bool: ...
    def stop(self) -> None: ...
    def ensure_enabled(self) -> bool: ...
    def set_hotkey(self, hotkey: str) -> None: ...


class Inserter(Protocol):
    def can_insert(self) -> bool: ...
    def frontmost_pid(self) -> int | None: ...
    def insert(self, text: str, settings: object, submit: bool) -> None: ...
    def copy(self, text: str) -> None: ...


class Feedback(Protocol):
    def play(self, sound: str) -> None: ...
    def notify(self, title: str, message: str) -> None: ...


class LoginItem(Protocol):
    def is_enabled(self) -> bool: ...
    def enable(self) -> None: ...
    def disable(self) -> None: ...


class Platform(Protocol):
    name: str  # "macOS" | "Linux"
    hotkey_labels: dict[str, str]  # hotkey id → label shown in the menu
    supports_hud: bool

    def runtime(self, on_ready: Action, on_quit: Action) -> Runtime: ...
    def tray(self, app: object) -> Tray: ...
    def hud(self) -> Hud: ...
    def hotkey(self, name: str, callback: Callable[[str, float], None]) -> HotkeyBackend: ...
    def inserter(self) -> Inserter: ...
    def feedback(self) -> Feedback: ...
    def login_item(self) -> LoginItem: ...
    def input_device_names(self) -> list[str]: ...
    def warnings(self, hotkey_running: bool) -> list[Warning]:
        """Problems to show at the top of the menu (missing permissions etc.)."""

    def request_permissions(self) -> None: ...
    def doctor(self) -> list[tuple[bool, str]]:
        """(ok, description) lines for `dikte doctor`."""
